import 'package:flutter/material.dart';


ThemeData dayTheme = ThemeData(
  useMaterial3: true,
  fontFamily: 'Lexend',
  colorScheme: ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFF7C846),
    onPrimary: Color(0xFF0E121A),
    //primaryContainer: Color(0xFF4F378B),
    onPrimaryContainer: Color(0xFF0E121A),
    secondary: Color(0xFFB00020),//0xFFB00020
    onSecondary: Color(0xFF0E121A),
    //secondaryContainer: Color(0xFF4A4458),
    onSecondaryContainer: Color(0xFF0E121A),
    tertiary: Color(0xFF8BE98E),
    onTertiary: Color(0xFF0E121A),
    //tertiaryContainer: Color(0xFF633B48),
    onTertiaryContainer: Color(0xFF0E121A),
    error: Color(0xFFB00020),
    onError: Color(0xFF0E121A),
    //errorContainer: Color(0xFF8C1D18),
    onErrorContainer: Color(0xFF0E121A),
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF0E121A),
    //surfaceContainerHighest: Color(0xFF49454F),
    //onSurfaceVariant: Color(0xFFCAC4D0),
    //outline: Color(0xFF938F99),
    //shadow: Colors.black,
    //inverseSurface: Color(0xFFE6E1E5),
    //onInverseSurface: Color(0xFF313033),
    //inversePrimary: Color(0xFF6750A4),
  ),
);

ThemeData nigthTheme = ThemeData(
  useMaterial3: true,
  fontFamily: 'Lexend',
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFF7C846),
    onPrimary: Color(0xFFFFFFFF),
    //primaryContainer: Color(0xFF4F378B),
    onPrimaryContainer: Color(0xFFFFFFFF),
    secondary: Color(0xFFB00020),//0xFFB00020
    onSecondary: Color(0xFFFFFFFF),
    //secondaryContainer: Color(0xFF4A4458),
    onSecondaryContainer: Color(0xFFFFFFFF),
    tertiary: Color(0xFF8BE98E),
    onTertiary: Color(0xFFFFFFFF),
    //tertiaryContainer: Color(0xFF633B48),
    onTertiaryContainer: Color(0xFFFFFFFF),
    error: Color(0xFFB00020),
    onError: Color(0xFFFFFFFF),
    //errorContainer: Color(0xFF8C1D18),
    onErrorContainer: Color(0xFFFFFFFF),
    surface: Color(0xFF0E121A),
    onSurface: Color(0xFFFFFFFF),
    //surfaceContainerHighest: Color(0xFF49454F),
    //onSurfaceVariant: Color(0xFFCAC4D0),
    //outline: Color(0xFF938F99),
    //shadow: Colors.black,
    //inverseSurface: Color(0xFFE6E1E5),
    //onInverseSurface: Color(0xFF313033),
    //inversePrimary: Color(0xFF6750A4),
  ),
);